name: CO2 Monitor
version: "1.0.8"
slug: co2mon
description: CO2 Monitor daemon for USB CO2 sensors (TFA AIRCO2NTROL MINI and compatible)
url: https://github.com/dmage/co2mon
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: system
boot: auto
init: false
privileged:
  - SYS_RAWIO
devices:
  - /dev/hidraw0
  - /dev/hidraw1
  - /dev/hidraw2
  - /dev/hidraw3
  - /dev/hidraw4
  - /dev/hidraw5
  - /dev/hidraw6
  - /dev/hidraw7
  - /dev/hidraw8
  - /dev/hidraw9
udev: true
options:
  device_path: "auto"
  metrics_port: 8080
schema:
  device_path: str
  metrics_port: "port"
ports:
  "8080/tcp": 8080
ports_description:
  "8080/tcp": "CO2 Monitor metrics endpoint"
ingress: true
ingress_port: 8080
panel_icon: mdi:molecule-co2
panel_title: CO2 Monitor
